### ISSUE TITLE
查询不到

### ISSUE THREAD

**Issue by kevin70** [juven/portable-config-maven-plugin#11]
<plugin>
                        <groupId>com.juvenxu.portable-config-maven-plugin</groupId>
                        <artifactId>portable-config-maven-plugin</artifactId>
                        <version>1.1.4</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>replace-package</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <packaging>war</packaging>
                            <portableConfig>src/main/portable/dist-portable.xml</portableConfig>
                        </configuration>
                    </plugin>

<config-file path="conf/beans-kernel.xml">
        <replace key="/beans/bean[@type='org.skfiy.typhon.script.ScriptManager']/@class">org.skfiy.typhon.script.ProductionScriptManager</replace>
#     </config-file>

-- end configuration --
Replacing: E:\Skfiy\typhon\typhon-kernel\target\typhon-kernel-1.0-SNAPSHOT
# Replacing file: E:\Skfiy\typhon\typhon-kernel\target\typhon-kernel-1.0-SNAPSHOT\conf\beans-kernel.xml

<beans>

```
<bean type="org.skfiy.typhon.session.SessionManager"
      class="org.skfiy.typhon.session.DefaultSessionManager"/>

<bean type="org.skfiy.typhon.ConnectionProvider"
      class="org.skfiy.typhon.database.BoneCPConnectionProvider"/>

<bean type="org.skfiy.typhon.dispatcher.DispatcherFactory"
      class="org.skfiy.typhon.dispatcher.ReflectionDispatcherFactory"/>

<bean type="org.skfiy.typhon.net.ProtocolHandler"
      class="org.skfiy.typhon.net.JsonProtocolHandler"/>

<bean type="org.skfiy.typhon.script.ScriptManager"
      class="org.skfiy.typhon.script.DebugScriptManager"/>
```

</beans>
# 

Caused by: java.lang.NullPointerException: Null query
    at org.jdom2.xpath.util.AbstractXPathCompiled.<init>(AbstractXPathCompiled.java:114)
    at org.jdom2.xpath.jaxen.JaxenCompiled.<init>(JaxenCompiled.java:148)
    at org.jdom2.xpath.jaxen.JaxenXPathFactory.compile(JaxenXPathFactory.java:82)
    at org.jdom2.xpath.XPathFactory.compile(XPathFactory.java:297)
    at com.juvenxu.portableconfig.filter.XmlContentFilter.filter(XmlContentFilter.java:66)
    at com.juvenxu.portableconfig.traverser.DirectoryTraverser.traverse(DirectoryTraverser.java:56)
    at com.juvenxu.portableconfig.DefaultPortableConfigEngine.doReplace(DefaultPortableConfigEngine.java:56)
    at com.juvenxu.portableconfig.DefaultPortableConfigEngine.replace(DefaultPortableConfigEngine.java:45)
    at com.juvenxu.portableconfig.mojo.PortableConfigReplacePackageMojo.execute(PortableConfigReplacePackageMojo.java:66)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)

**Comment by kevin70** [comment]
<portable-config>
    <config-file path="conf/beans-kernel.xml">
        <replace key="/beans/bean[@type='org.skfiy.typhon.script.ScriptManager']/@class">org.skfiy.typhon.script.ProductionScriptManager</replace>
    </config-file>
</portable-config>
